### GET RIDER COORDINATES
GET http://localhost:3002/rider-coordinates

### CREATE RIDER COORDINATES
POST http://localhost:3002/rider-coordinates
Content-Type: application/json

{
    "lat": 1213.23,
    "lng": 143551.21,
    "riderId": "dasdsd"
}